openapi: 3.0.3
info:
  title: "Facturas AOS"
  description: "Especificacion facturas para la asignatura AOS"
  version: "v1"
servers:
  - url: '{schema}://{server}:{port}/{basePath}'
    description: Servidor local
    variables:
      schema:
        description: Esquema
        default: http
        enum:
          - http
          - https
      server:
        description: Nombre del servidor
        default: 127.0.0.1
      port:
        description: Número de puerto
        default: '80'
      basePath:
        description: Ruta base
        default: api/v1
tags:
  - name: 'Factura'
    description: Factura con el conjunto de trabajos realizados en un vehiculo
paths:
  /factura:
    get:
      tags: 
      - 'Factura'
      summary: Obtiene todas las facturas
      operationId: upm_aos_facturas_get
      responses:
        200:
          description: Array de facturas
          headers:
            ETag:
              $ref: '#/components/headers/ETag'
          content:
            application/json:
                schema:
                    type: object
                    properties:
                        facturas:
                            description: array de facturas
                            type: array
                            items:
                                $ref: '#/components/schemas/Factura'
                examples:
                    facturasExamples:
                        $ref: '#/components/examples/facturas'
        404:
          $ref: '#/components/responses/Response_404'
    post:
      tags: 
      - 'Factura'
      summary: Genera la factura de un usuario
      description: Genera la factura con un conjunto de trabajos y un importe.
      operationId: upm_aos_factura_post
      requestBody:
        $ref: '#/components/requestBodies/facturaPostRB'
      responses:
        '201':
          description: Factura
          headers:
            Location:
              $ref: '#/components/headers/Location'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Factura'
        '404':
          $ref: '#/components/responses/Response_404'
    options:
      tags: 
      - 'Factura'
      summary: Proporciona la lista de los métodos HTTP soportados.
      description: Devuelve una cabecera `Allow` con la lista de métodos HTTP soportados (separados por comas).
      operationId: upm_aos_factura_options
      responses:
        '204':
          description: 'cabecera `Allow` &lt;El cuerpo de la respuesta está vacío&gt;'
          headers:
            Allow:
              $ref: '#/components/headers/Allow'
          
  /factura/facturaId/{facturaId}:
    parameters:
      - $ref: '#/components/parameters/facturaId'
    get:
      tags: 
      - 'Factura'
      summary: Obtiene una factura por su ID
      description: Obtiene una factura identificada por su facturaID.
      operationId: upm_aos_factura_fget
      responses:
        '200':
          description: Factura
          headers:
            ETag:
              $ref: '#/components/headers/ETag'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Factura'
        '404':
          $ref: '#/components/responses/Response_404'
    delete:
      tags: 
      - 'Factura'
      summary: Elimina una factura.
      description: Elimina la factura identificada por facturaId
      operationId: upm_aos_factura_delete
      responses:
        '204':
          description: Factura eliminada &lt;Cuerpo de la respuesta vacío&gt;
        '404':
          $ref: '#/components/responses/Response_404'
    put:
      tags: 
      - 'Factura'
      summary: Modifica la factura.
      description: Actualiza la factura identificada por facturaId.
      operationId: upm_aos_factura_put
      parameters:
        - $ref: '#/components/parameters/ifMatchParam'
      requestBody:
        $ref: '#/components/requestBodies/facturaPutRB'
      responses:
        '200':
          description: '`OK`: la factura ha sido modificada'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Factura'
        '404':
          $ref: '#/components/responses/Response_404'
        '412':
          $ref: '#/components/responses/Response_412'
    options:
      tags: 
      - 'Factura'
      summary: Proporciona la lista de los métodos HTTP soportados.
      description: Devuelve una cabecera `Allow` con la lista de métodos HTTP soportados (separados por comas).
      operationId: upm_aos_factura_foptions
      responses:
        '204':
          description: 'cabecera `Allow` &lt;El cuerpo de la respuesta está vacío&gt;'
          headers:
            Allow:
              $ref: '#/components/headers/Allow'

  /factura/vehiculoId/{vehiculoId}:
    parameters:
      - $ref: '#/components/parameters/vehiculoId'
    get:
      tags: 
      - 'Factura'
      summary: Obtiene todas las facturas de un vehiculo
      description: Obtiene todas las facturas de un vehiculo por su vehiculoId
      operationId: upm_aos_factura_vget
      responses:
        '200':
          description: Factura
          headers:
            ETag:
              $ref: '#/components/headers/ETag'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Factura'
        '404':
          $ref: '#/components/responses/Response_404'
    options:
      tags: 
      - 'Factura'
      summary: Proporciona la lista de los métodos HTTP soportados.
      description: Devuelve una cabecera `Allow` con la lista de métodos HTTP soportados (separados por comas).
      operationId: upm_aos_factura_voptions
      responses:
        '204':
          description: 'cabecera `Allow` &lt;El cuerpo de la respuesta está vacío&gt;'
          headers:
            Allow:
              $ref: '#/components/headers/Allow'
  /factura/userId/{userId}:
    parameters:
      - $ref: '#/components/parameters/userId'
    get:
      tags: 
      - 'Factura'
      summary: Obtiene todas las facturas de un usuario
      description: Obtiene todas las facturas de un usuario por su userId
      operationId: upm_aos_factura_uget
      responses:
        '200':
          description: Factura
          headers:
            ETag:
              $ref: '#/components/headers/ETag'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Factura'
        '404':
          $ref: '#/components/responses/Response_404'
    options:
      tags: 
      - 'Factura'
      summary: Proporciona la lista de los métodos HTTP soportados.
      description: Devuelve una cabecera `Allow` con la lista de métodos HTTP soportados (separados por comas).
      operationId: upm_aos_factura_uoptions
      responses:
        '204':
          description: 'cabecera `Allow` &lt;El cuerpo de la respuesta está vacío&gt;'
          headers:
            Allow:
              $ref: '#/components/headers/Allow'

components:
  schemas:
    Factura:
      type: object
      description: Documento que refleja un conjunto de trabajos realizados en un vehiculo
      properties:
        facturaId:
          description: Id Factura
          readOnly: true
          type: integer
          format: int32
        userId:
          description: user Id
          readOnly: true
          type: integer
          format: int32
        vehiculoId:
          description: Id vehiculo
          readOnly: true
          type: integer
          format: int32
        fechaEmision:
          description: Fecha de creacion de la factura
          readOnly: true
          type: string
          format: date
          #El formato date tiene un patron "YYYY-MM-DD"
        importe:
          description: Importe total
          readOnly: false
          type: number
        importeIVA:
          description: Importe con IVA
          readOnly: false
          type: number
        links:
            description: Listado de trabajos
            type: array
            items:
              type: object
              description: Enlace de relación
              properties:
                href:
                  description: URL del enlace
                  type: string
                  format: url
                  x-faker: internet.url
                rel:
                  description: "Relación del documento enlazado con el actual. Contiene una lista de tipos de enlaces separados por espacio."
                  type: string
                  x-faker: lorem.words
      example:
        facturaId: 5623
        userId: 21
        vehiculoId: 67
        fechaEmision: "2021-03-29"
        importe: 234
        iporteIVA: 283.14
        links:
          # - href: /api/v1/trabajo/iDTrabajo
          - href: api/v1/trabajo/1111
            rel: trabajo
          - href: api/v1/trabajo/1112
            rel: trabajo
    HTTP_Problem:
      type: object
      externalDocs:
        url: https://tools.ietf.org/html/rfc7807
      description: Problem Details for HTTP APIs
      properties:
        type:
          type: string
          format: uri
          description: A URI reference [RFC3986] that identifies the problem type
        title:
          type: string
          description: short human-readable summary of the problem type
        status:
          type: number
          description: HTTP status code
        detail:
          type: string
          description: human-readable explanation specific to this occurrence of the problem
        instance:
            type: string
            format: uri
            description: "A URI reference that identifies the specific
            occurrence of the problem.  It may or may not yield further
            information if dereferenced"

  headers:
    ETag:
      description: Entity Tag (identificador único proporcionado para validación de caché)
      schema:
        type: string
        pattern: "[0-9a-f]*"
        x-faker: random.uuid
        example:
          0242ac130003abs3
    Location:
      description: '`URI` del nuevo recurso'
      schema:
        type: string
        format: url
        x-faker: internet.url
        example:
          /api/v1/factura/5623
    Allow:
      description: Lista de métodos HTTP soportados
      schema:
        type: string
      example:
        GET,DELETE,PUT,OPTIONS
        
  parameters:
    facturaId:
      name: facturaId
      in: path
      description: ID de la factura
      required: true
      schema:
        type: integer
        pattern: ^\d+$
    ifMatchParam:
      name: If-Match
      in: header
      description: ETag del recurso que se desea modificar
      required: true
      schema:
        type: string
        pattern: "[0-9a-f]*"
    vehiculoId:
      name: vehiculoId
      in: path
      description: ID del vehiculo
      required: true
      schema:
        type: integer
        pattern: ^\d+$
    userId:
      name: userId
      in: path
      description: ID del usuario
      required: true
      schema:
        type: integer
        pattern: ^\d+$

  requestBodies:
    facturaPostRB:
      description: '`Factura` data'
      required: true
      content:
        application/json:
          schema:
            type: object
            required:
              - facturaId
              - userId
              - vehiculoId
              - fechaEmision
              - importe
              - importeIVA
              - links
            properties:
                facturaId:
                    description: Id Factura
                    readOnly: true
                    type: integer
                    format: int32
                userId:
                    description: user Id
                    readOnly: true
                    type: integer
                    format: int32
                vehiculoId:
                    description: Id vehiculo
                    readOnly: true
                    type: integer
                    format: int32
                fechaEmision:
                    description: Fecha de creacion de la factura
                    readOnly: true
                    type: string
                    format: date
                    #El formato date tiene un patron "YYYY-MM-DD"
                importe:
                    description: Importe total
                    readOnly: true
                    type: number
                importeIVA:
                    description: Importe con IVA
                    readOnly: true
                    type: number
                links:
                    description: Listado de trabajos
                    type: array
                    items:
                      type: object
                      description: Enlace de relación
                      properties:
                        href:
                          description: URL del enlace
                          type: string
                          format: url
                          x-faker: internet.url
                        rel:
                          description: "Relación del documento enlazado con el actual. Contiene una lista de tipos
                          de enlaces separados por espacio."
                          type: string
                          x-faker: lorem.words
            example:
                facturaId: 34212
                userId: 23
                vehiculoId: 1234
                fechaEmision: "2021-11-21"
                importe: 590.45
                importeIVA: 714.45
                links:
                    # - href: /api/v1/trabajo/iDTrabajo
                    - href: /api/v1/trabajo/1111
                      rel: trabajo
                    - href: /api/v1/trabajo/1112
                      rel: trabajo
                    - href: /api/v1/trabajo/1113
                      rel: trabajo
    facturaPutRB:
      description: '`Factura` data'
      required: true
      content:
        application/json:
          schema:
            type: object
            required:
              - importe
              - importeIVA
            properties:
              importe:
                description: Importe de la factura sin IVA
                type: number
              importeIVA:
                description: Importe de la factura con IVA
                type: number
            example:
              importe: 237.98
              importeIVA: 287.96
  
  responses:
    Response_404:
      description: '`NOT FOUND`: recurso no disponible'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/HTTP_Problem'
          examples:
            response-http-404:
              $ref: '#/components/examples/response-http-404'
    Response_412:
      description: '`PRECONDITION FAILED`: no se cumple alguna condición previa'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/HTTP_Problem'
          examples:
            response-http-412:
              $ref: '#/components/examples/response-http-412'
    Response_422:
      description: '`UNPROCESSABLE ENTITY`: falta la referencia o las unidades'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/HTTP_Problem'
          examples:
            response-http-422:
              $ref: '#/components/examples/response-http-422'
              
  examples:
    facturas:
      value:
        - facturaId: 5623
          userId: 21
          vehiculoId: 67
          fechaEmision: "2021-03-29"
          importe: 234
          iporteIVA: 283.14
          links:
            - href: api/v1/trabajo/1111
              rel: trabajo
            - href: api/v1/trabajo/1112
              rel: trabajo
        - facturaId: 1345
          userId: 12
          vehiculoId: 15
          fechaEmision: "2020-07-13"
          importe: 567.94
          iporteIVA: 723.50
          links:
            - href: api/v1/trabajo/1113
              rel: trabajo
    response-http-404:
      value:
        type: https://httpstatuses.com/404
        title: NOT FOUND
        status: 404
        detail: El recurso solicitado no está disponible...
        instance: about:blank
    response-http-412:
      value:
        type: https://httpstatuses.com/412
        title: PRECONDITION FAILED
        status: 412
        detail: No se cumple alguna condición previa...
        instance: about:blank
    response-http-422:
      value:
        type: https://httpstatuses.com/422
        title: UNPROCESSABLE ENTITY
        status: 422
        detail: Falta la referencia o las unidades...
        instance: about:blank
    
